#!/bin/bash -x
magic='# generated by make-lib-extras.sh'
grep -l -F -e "$magic" lib*_extras 2>/dev/null | xargs -rt rm --
grep -E -e '/usr/lib64/lib(LLVM|clang).*\.so\.' *.spec | while read f; do
    ef=${f##*/}
    ef=${ef%.so.*}
    ef=${ef,,*}
    printf '%s\n%s\n' "$magic" "$f" > ${ef}_extras
done

